---
- name: mysql-server install
  yum: name={{ item }} state=installed
  with_items:
    - mysql
    - mysql-devel
    - mysql-server

- name: copy my.cnf
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
    - restart mysqld

- name: mysqld is started and enabled
  service: name=mysqld state=started enabled=yes

- include: mysql_secure_installation.yml
  when: mysql_secure_installation and mysql_root_password is defined
